const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const loader = fs.readFileSync(path.join(root, 'loader.js'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'pinned-user.json'), 'utf8'));
function boot() {
    let resolve, reject, stop;
    const state = {buttons:[{name:'🔄 检查更新'},{name:'📌 常用 User'},{name:'custom'}],calls:0,warnings:[],urls:[]};
    const window = {addEventListener:(event,callback)=>{stop=callback;},toastr:{warning:msg=>state.warnings.push(msg)}};
    window.parent=window;
    vm.runInNewContext(loader.replace('import(url)', 'loadModule(url)'), {
        window, console,
        getScriptButtons:()=>state.buttons,
        replaceScriptButtons:buttons=>{state.buttons=buttons;},
        loadModule:url=>{state.urls.push(url);return new Promise((yes,no)=>{resolve=yes;reject=no;});},
    });
    return {state,stop:()=>stop(),resolve:version=>resolve({version,default:()=>state.calls++}),reject:()=>reject(new Error('offline'))};
}
const settle = () => new Promise(resolve => setImmediate(resolve));
test('JSON contains version-pinned loader and module is generated from current source', () => {
    assert.equal(pkg.content, loader);
    assert.ok(loader.includes(`const VERSION = '${pkg.version}';`));
    const source=fs.readFileSync(path.join(root,'pinned-user.js'),'utf8');
    const module=fs.readFileSync(path.join(root,'pinned-user.module.js'),'utf8');
    assert.equal(module,`// Generated by scripts/build.cjs; do not edit.\nexport const version = '${pkg.version}';\nexport default function startPinnedUser() {\n${source}\n}\n`);
});
test('loader removes only obsolete button and starts exact version without script-tree APIs', async () => {
    const h=boot();
    assert.equal(JSON.stringify(h.state.buttons.map(b=>b.name)), '["📌 常用 User","custom"]');
    assert.ok(h.state.urls[0].includes(`@v${pkg.version}/pinned-user.module.js`));
    h.resolve(pkg.version);await settle();assert.equal(h.state.calls,1);
});
test('disabled during download does not start late or show warning', async () => {
    const h=boot();h.stop();h.resolve(pkg.version);await settle();
    assert.equal(h.state.calls,0);assert.deepEqual(h.state.warnings,[]);
});
test('network failure and mismatched module version do not start runtime', async () => {
    const a=boot();a.reject();await settle();assert.equal(a.state.calls,0);assert.equal(a.state.warnings.length,1);
    const b=boot();b.resolve('0.0.0');await settle();assert.equal(b.state.calls,0);assert.equal(b.state.warnings.length,1);
});
